### ISSUE TITLE
Linux - Startup fails on Sasquatch 06/2021 Release with Required module DefaultPermissionsModule not found

### ISSUE THREAD

**Issue by sarapayne** [OpenSim-NGC/OpenSim-Sasquatch#34]
This has to be configuration dependant since Mike has it working. However, my configuration works with Sasquatch 05/2021 Release Hotfix 1, Sasquatch 05/2021  and Opensim-Core. 

In all versions of Sasquatch, the configuration is the same, with Opensim-Core it just lacks the globit config files and dll. Logs Attached. 

[05-2021-release - Pass.txt](https://github.com/OpenSim-NGC/OpenSim-Sasquatch/files/6866143/05-2021-release.-.Pass.txt)
[06-2021 Release - Fail.txt](https://github.com/OpenSim-NGC/OpenSim-Sasquatch/files/6866144/06-2021.Release.-.Fail.txt)
[Opensim-Core-07-2011 - Pass.txt](https://github.com/OpenSim-NGC/OpenSim-Sasquatch/files/6866145/Opensim-Core-07-2011.-.Pass.txt)

**Opensim.exe Permions Section**
[Permissions]
    permissionmodules = DefaultPermissionsModule
    serverside_object_permissions = true
    allow_grid_gods = true
    region_owner_is_god = false
    region_manager_is_god = false

**Comment by mdickson** [comment]
You're definitely using the same config for all these cases?  It looks like the regions are different at a minimum.  I'll follow up with you and see if I can get the config you're using. I need to replicate this error to fix it.

**Comment by sarapayne** [comment]
Sometimes a video makes things clear when demonstrating consistency. This is exactly the same configuration. 

[startup-fail-Demonstration.tar.gz](https://github.com/OpenSim-NGC/OpenSim-Sasquatch/files/6867067/startup-fail-Demonstration.tar.gz)

I forgot to add the globit.ini file into the bin folder in the last demo, but it still gives the same result. 

I will sort out a cleaned-up version of my config so the passwords and stuff are removed.

**Comment by mdickson** [comment]
Ok I've replicated as best I can your config. With permissions explicitely enabled but no issue so this doesn't appear to be a simple config issue.  The logs are very different when modules get loaded.  So I'm wondering if its a loading issue.  There have been changes in that area.  

When you start OpenSim do you run *from* the binary directory?   I do something like ....

(cd $BASEDIR && Opensim.exe)  vs $BASEDIR/OpenSim.exe where you might not be in the actual directory the code is in.

**Comment by sarapayne** [comment]
3 Consecutive runs log. The first has no globits.ini and neither does the 2nd, for completeness the 3rd log includes the Globit.ini file. 

The first log is different to the subsequent ones but the end result is the same. 

[3-Consecutive-Run-Logs.tar.gz](https://github.com/OpenSim-NGC/OpenSim-Sasquatch/files/6870034/3-Consecutive-Run-Logs.tar.gz)

**Comment by sarapayne** [comment]
After following @mdickson 's advice I ran robust instances on the same bin folder. This worked on the 2nd attempt. Robust launches correctly. 

The simulator is still failing but its now different. 
[Simulator10.log](https://github.com/OpenSim-NGC/OpenSim-Sasquatch/files/6872711/Simulator10.log)

**Comment by sarapayne** [comment]
I removed my last comment, that change was a user error. I had added in the external name for lsl but not changed the variable. Robust starts successfully other than on the first run. However, I am still getting exactly the same results as previous attempts for simulators. I also replaced the bin folder again to confirm I can still run the previous version and I can.

**Comment by KayakerMagic** [comment]
I just cloned a new copy of NGC today, got it to build on an Ubuntu 18.04 system, tried to test it and got the same error about DefaultPermissionsModule. I run from the binary directory and reach out to a folder with specifics for each region.
Tried this after building the Debug and the Release version, same result. Log from the last try:
[OpenSim.log.txt](https://github.com/OpenSim-NGC/OpenSim-Sasquatch/files/6890701/OpenSim.log.txt)

**Comment by sarapayne** [comment]
During config reading the default permissions string is set correctly, however it looks as though the fault is more generic and this is just the one that gets picked up. 

OpenSimBase.cs at line 455

`if (m_securePermissionsLoading)
            {
                foreach (string s in m_permsModules)
                {
                    if (!scene.RegionModules.ContainsKey(s))
                    {
                        m_log.Fatal("[MODULES]: Required module " + s + " not found.");
                        Environment.Exit(0);
                    }
                }

                m_log.InfoFormat("[SCENE]: Secure permissions loading enabled, modules loaded: {0}", String.Join(" ", m_permsModules.ToArray()));
            }scene.RegionModules = {Dictionary<string, IRegionModuleBase>} Count = 0`

The dictionary at this point is empty, it has no entries 

![empty dictionary](https://user-images.githubusercontent.com/56539249/127281348-f78edb4b-fd1e-425d-ac34-846193ab0969.png)

unless that dictionary is supposed to contain just one entry this fault is not really related to default permissions at all

**Comment by sarapayne** [comment]
So i started comparing launching OpenCore against the lastest sasquatch to find where it goes wrong. 

ServerUtils.cs Line 273

`public static T LoadPlugin<T>(string dllName, string className, Object[] args) where T:class
        {
            string interfaceName = typeof(T).ToString();

            try
            {
                Assembly pluginAssembly = Assembly.LoadFrom(dllName);

                foreach (Type pluginType in pluginAssembly.GetTypes())
                {
                    if (pluginType.IsPublic)
                    {
                        if (className != String.Empty
                            && pluginType.ToString() != pluginType.Namespace + "." + className)
                            continue;

                        Type typeInterface = pluginType.GetInterface(interfaceName);

                        if (typeInterface != null)
                        {
                            T plug = null;
                            try
                            {
                                plug = (T)Activator.CreateInstance(pluginType,
                                        args);
                            }
                            catch (Exception e)
                            {
                                if (!(e is System.MissingMethodException))
                                {
                                    m_log.Error(string.Format("[SERVER UTILS]: Error loading plugin {0} from {1}. Exception: {2}",
                                        interfaceName,
                                        dllName,
                                        e.InnerException == null ? e.Message : e.InnerException.Message),
                                            e);
                                }
                                m_log.ErrorFormat("[SERVER UTILS]: Error loading plugin {0}: {1} args.Length {2}", dllName, e.Message, args.Length);
                                return null;
                            }

                            return plug;
                        }
                    }
                }

                return null;
            }
            catch (ReflectionTypeLoadException rtle)
            {
                m_log.Error(string.Format("[SERVER UTILS]: Error loading plugin from {0}:\n{1}", dllName,
                    String.Join("\n", Array.ConvertAll(rtle.LoaderExceptions, e => e.ToString()))),
                    rtle);
                return null;
            }
            catch (Exception e)
            {
                m_log.Error(string.Format("[SERVER UTILS]: Error loading plugin from {0}", dllName), e);
                return null;
            }
        }`

Assembly pluginAssembly = Assembly.LoadFrom(dllName); 

On Opensim core this works, however, in the latest sasquatch, it fails and jumps to the catch. Have there been changes inside the dll?

**Comment by sarapayne** [comment]
There are a lot of dll's missing from the debug build. They are present in the release build. When launching the same error is reported in both release and debug. 

I also tried debugging the release build. Which does produce the dll file. When the foreach loop is entered in sasquatch there is only one pluginType, where as in the OpenSim core build there are many, this is where the problem lies.

**Comment by mdickson** [comment]
Some more information.  All of the plugin types that do work (Robust, RegionServer Startup, etc) use a Plugin Loader in OpenSIm. Framework to load plugins. This appears to function ok.  The RegionModule loader (which is itself a plugin and was loaded from the PluginManager) directly interfaces with Mono.Addins (as does the Wind modules btw).  I'm looking at reworking the Module loader a bit to use the Framework classes. I still don't have a handle on why it works on my grid environments but not on others. I've reviewed things looking for environmental differences but can't see anything.   Going to continue that effort as well while I rework the module loader.

**Comment by sarapayne** [comment]
Following a lot of work by @mdickson  this issue is resolved at some point before commit [e8d271f](https://github.com/OpenSim-NGC/OpenSim-Sasquatch/commit/e8d271fd92e9a2f33e61162bfec9eb12eae58f68)
